# Generated by Django 3.1.5 on 2021-02-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetphilani', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collaborations',
            new_name='Collaboration',
        ),
        migrations.RenameModel(
            old_name='Technology',
            new_name='Technologie',
        ),
    ]
