# Generated by Django 3.1.5 on 2021-02-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetphilani', '0002_auto_20210205_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_upload', models.FileField(upload_to='media')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
